### ISSUE TITLE
Messages Cannot be Sent via AJAX

### ISSUE THREAD

**Issue by SDey96** [SDey96/open-learning#2]
Whenever I try sending messages through `profile.php`, it returns an uncertain error. The concerned form's ID is `#message-form`.

**Steps to reproduce the error:**
1. Import the SQL queries from `openlearn.sql`, if not already done.
2. In the URL, type "`localhost/open-learning/profile.php?instructor_email=username@domain.com`" (The email must exist in the `Instructor` table.).
3. Click on "Send Message", fill out all the fields, and click on "Send".

**Concerned files are:** 
1. `profile.php`: The concerned page.
2. `send-message.js`: Contains AJAX code.
3. `send-message.php`: contains the PHP code for updating data into the `Messages` table.

**Comment by SDey96** [comment]
@eliandoran I apologise for bothering you too much, but this is serious. Can you please help me debug it?

**Comment by eliandoran** [comment]
For AJAX requests, you can use my debugging method.

The first thing is that you need to reduce the logic being tested as much as possible. In order to do that, you need to test the front-end AJAX request (i.e. the methods that take the form information and submits an AJAX request) and the back-end separately.

To test the back-end separately, without the front-end you need a method for access. One such method is to reproduce the AJAX call by using an API tester. The application that I have used for testing your previous issue was https://www.getpostman.com/ and I warmly recommend it.

Install Postman and start making "AJAX" requests from the app so that you can test it independently of your HTML interface.

**Comment by SDey96** [comment]
The front-end AJAX is working fine; the backend, however, is not.

In the Postman app, I tested `send-message.php` and `profile.php` under 'JSON' category. 
`profile.php` returns: 
`Unexpected '<'`

`send-message.php` returns the following:
```
{
    "status": "error",
    "message": "<span class=\"glyphicon glyphicon-info-sign\"></span> &nbsp; Could not send your message. Please try again later.",
    "query": null
}
```

Now where do I resolve the issue?

**Comment by eliandoran** [comment]
I have come into this issue myself, as well. Use the "Raw" tab, instead of the "Pretty" tab whilst viewing data.

**Comment by eliandoran** [comment]
Also, check your PHP error log. For example, you have forgot to include `config.php`, leading to there being no `$link` to the database, thus rendering your code useless.

**Comment by eliandoran** [comment]
@SDey96 , what's this query supposed to do?
`INSERT INTO messages VALUES ('59fdbd2d84f55', 'Jesus H. Christ', 'jesus@christ.corp', 'Hello world!', NOW(), 'elinnum@gmail.com' WHERE instructor_email='elinnum@gmail.com')`

**Comment by SDey96** [comment]
It is supposed to store messages into the `Messages` table.

**Comment by eliandoran** [comment]
How exactly, @SDey96 ? `INSERT` statements have no `WHERE` clause, as far as I am aware of.

**Comment by SDey96** [comment]
Oh, I am sorry, MySQL does not support `WHERE` clause in `INSERT` statements. Even if it did, the statement would be pretty dumb. 

Although I removed it, yet it does not work.

**Comment by eliandoran** [comment]
You had a point there, but you did a number of mistakes.
You would need to use subqueries for this, an example of a working SQL would be:

```INSERT INTO `messages` VALUES ('59fdbffcab0f6', 'Jesus H. Christ', 'jesus@christ.corp', 'Hello world!', NOW(), (SELECT `id` FROM `instructor` WHERE `email`='elinnum@gmail.com'))```

Also, do note that your `messages`.`instructor_email`, according to a FK constraint you have made actually points to `instructor`.`id`, which is a good thing but the name is misleading.

**Comment by SDey96** [comment]
I think I made some logical error in the statement. I am currently finding it and will update once I find the root cause.

**Comment by SDey96** [comment]
`$query = "INSERT INTO messages VALUES ('$message_id', '$student_name', '$student_email', '$student_message', NOW(), '$inst_id')";`

**Comment by eliandoran** [comment]
I have sent you a Pull Request, please see to it, @SDey96 .

**Comment by SDey96** [comment]
Okay.

**Comment by SDey96** [comment]
It says that the repository is already "up-to-date".

**Comment by SDey96** [comment]
By the way, I changed the statement to this: `$query = "INSERT INTO messages VALUES ('$message_id', '$student_name', '$student_email', '$student_message', NOW(), '$inst_id')";` so that the foreign key would refer to its parent's `ID` column.

**Comment by eliandoran** [comment]
I solved the merge conflict for you, my code base should be working. If you want to edit your own version, no problem.

**Comment by SDey96** [comment]
I didn't see that you created a new branch. I will look into it and will thereby update it.

**Comment by SDey96** [comment]
Unfortunately, it still does not work.

**Comment by eliandoran** [comment]
What doesn't?

**Comment by eliandoran** [comment]
Make a `POST` request to `send-message.php` containing the following Body (`form-data`) using Postman:

`senderName`=`Hello World`
`senderEmail`=`hello@world.com`
`senderMessage`=`Hello, World`
`instEmail`=_your email_

**Comment by eliandoran** [comment]
You can also add a `die($query)` right after the query declaration to see if the SQL query is generated correctly, @SDey96 .

**Comment by SDey96** [comment]
In PHP's error log: ```
[Sat Nov 04 19:50:29.682774 2017] [:error] [pid 23536] [client ::1:43852] PHP Notice:  Undefined index: id in /var/www/html/open-learning/profile.php on line 13
[Sat Nov 04 19:50:46.366418 2017] [:error] [pid 23537] [client ::1:43858] PHP Notice:  Undefined variable: inst_id in /var/www/html/open-learning/send-message.php on line 16, referer: http://localhost/open-learning/profile.php?instructor_email=contact.sdey@gmail.co
[Sat Nov 04 19:50:46.366478 2017] [:error] [pid 23537] [client ::1:43858] PHP Notice:  Undefined variable: link in /var/www/html/open-learning/send-message.php on line 18, referer: http://localhost/open-learning/profile.php?instructor_email=contact.sdey@gmail.co
[Sat Nov 04 19:50:46.366497 2017] [:error] [pid 23537] [client ::1:43858] PHP Warning:  mysqli_query() expects parameter 1 to be mysqli, null given in /var/www/html/open-learning/send-message.php on line 18, referer: http://localhost/open-learning/profile.php?instructor_email=contact.sdey@gmail.co
[Sat Nov 04 19:50:46.366511 2017] [:error] [pid 23537] [client ::1:43858] PHP Notice:  Undefined variable: link in /var/www/html/open-learning/send-message.php on line 26, referer: http://localhost/open-learning/profile.php?instructor_email=contact.sdey@gmail.co
[Sat Nov 04 19:50:46.366520 2017] [:error] [pid 23537] [client ::1:43858] PHP Warning:  mysqli_error() expects parameter 1 to be mysqli, null given in /var/www/html/open-learning/send-message.php on line 26, referer: http://localhost/open-learning/profile.php?instructor_email=contact.sdey@gmail.co
```

**Comment by SDey96** [comment]
Now I got where the issue lies.

**Comment by SDey96** [comment]
I replaced `$getinfo = "SELECT name, email, website, twitter, picture, about from instructor where email='$instructor_email'";`
with 
`$getinfo = "SELECT name, id, email, website, twitter, picture, about from instructor where email='$instructor_email'";`

Yet it does not resolve the issue. And, sadly, now the logging also does not work.

**Comment by eliandoran** [comment]
Solve your `undefined variable`'s.
You have no `$link` because `config.php` was not included or it was not loaded properly.
Also you don't need `inst_id` if you use the method I used.
Take a look at my `send-message.php`: https://github.com/eliandoran/open-learning/blob/master/send-message.php

**Comment by SDey96** [comment]
Why do I need to include `config.php` twice? 
If I included it in the parent file `profile.php`, then is it also required to include it again in `send-message.php`?

**Comment by eliandoran** [comment]
Because both AJAX and Postman make an independent request to `send-message.php`, `profile.php` doesn't even exist in this context.

Also, each URL request to a PHP file gets their own context, o you cannot access anything from any other file unless you have explicity included them in the "main file". Your "main file" in this case is `send-message.php`, not `profile.php`.

**Comment by SDey96** [comment]
I have updated the table again as per my requirements, and also included `config.php` in `send-message.php`, yet I get an error.

**Comment by eliandoran** [comment]
Could you be more specific?

**Comment by SDey96** [comment]
Just checkout `openlearn.sql`.

**Comment by SDey96** [comment]
By the way, now the log shows only one error:
`[Sat Nov 04 20:22:28.529873 2017] [:error] [pid 25034] [client ::1:44336] PHP Notice:  Undefined variable: inst_id in /var/www/html/open-learning/send-message.php on line 18, referer: http://localhost/open-learning/profile.php?instructor_email=contact.sdey@gmail.co`

**Comment by SDey96** [comment]
With regard to the aforementioned log, can you tell me how do I pass on the value of `$inst_id` from `profile.php` to `send-message.php`?

**Comment by eliandoran** [comment]
You pass either the ID or the e-mail of the instructor either by POST or GET.

**Comment by SDey96** [comment]
Can you be a little explicit, please?

**Comment by SDey96** [comment]
Should I use ``<input type="hidden">``?

**Comment by eliandoran** [comment]
Just as you've passed the `senderName`, `senderEmail` and `senderMessage` through the `<form>`, you can use a `<input type="hidden" name="instEmail" value="<?= $instEmail ?> />` and you're all set.

**Comment by SDey96** [comment]
> Just as you've passed the senderName, senderEmail and senderMessage through the <form>, you can use a <input type="hidden" name="instEmail" value="<?= $instEmail ?>" /> and you're all set.

Yeah, I got this point already.

> Also, of course, don't forget to read it back in the `send-message.php`.
I don't understand you. Please be more specific.

**Comment by SDey96** [comment]
@eliandoran I did make changes as you requested, and yet getting errors. I also checked the error log, but it does not generate any error now.

**Comment by eliandoran** [comment]
If you managed to send it by POST via a hidden field all you need to do is:
`$instEmail = $_POST["instEmail"]`.

**Comment by eliandoran** [comment]
Well, how do you get errors without getting errors, @SDey96 ?

**Comment by SDey96** [comment]
To be honest, I don't know! I just feel unlucky now.

**Comment by SDey96** [comment]
@eliandoran Can you please have a final look at all the three files and diagnose what's causing the issue? I really want it to resolve by today anyhow.

**Comment by eliandoran** [comment]
Do something so I can push to the repository directly.

**Comment by SDey96** [comment]
I have pushed all the latest commits to my repository.

**Comment by SDey96** [comment]
Please look into it.

**Comment by SDey96** [comment]
> Do something so I can push to the repository directly.

What do you want me to do?

**Comment by eliandoran** [comment]
# My debug process

1. Clone your repository so I had the exact copy you have.
2. Set up the PHP server.
3. Edit config.php to match my server's credentials.
4. Use Postman to submit a POST request to `send-message.php` using `senderName`, `senderEmail`, `instID`
5. Observe the fact that it outputs the error message with no PHP errors.
6. Put `die($query)` right after the `$query` is initialized to see the problem with the query.
7. The output was: `INSERT INTO `messages` VALUES ('59fddfca7a9d0', 'Example', 'a@b.com', 'Hello world', NOW(), 59fdb9934c47f)`. Notice the lack of quotation marks for the ID.
8. Add the missing quotation marks to the query.
9. Run the request but notice nothing happens. Add `die(mysqli_error($link));` right after `mysqli_query` to output any possible MySQL errors.
10. Notice `Duplicate entry '59' for key 'PRIMARY'` gets outputted.
11. Scratch head.
12. Look at the database and notice someone made `message_id` an `INT` but forgot about it. The `uniqid` would generate a string whose first two characters (which happen to be a number) are the same, resulting in a duplicate entry MySQL error. 
13. Alter the table to make `message_id` a `VARCHAR(13)`.
14. POSTing `send-message.php` now works. :)

**Comment by eliandoran** [comment]
@SDey96 , now implement my findings. Please don't mess it up. 👍

**Comment by eliandoran** [comment]
![In case you need a refresher of how to configure the Postman request](https://user-images.githubusercontent.com/21236836/32406896-ef7c1ef6-c188-11e7-9aa0-12337992f88c.png)

**Comment by SDey96** [comment]
Damn! All of my code was correct, but mistakenly I used `int` instead of `varchar` for the `message_id` attribute of the `messages` table. I altered it to `varchar` and now it works! 

Guess what? I have been short of sleep lately and this is a result of it.

Thank you very much for pointing out the error, @eliandoran! The issue is resolved now.
